import dmk
import math

quiz1 = {
    "boss":"cocoa",
    "source":{
        "pixel":[
            "test/imgs/Cocoa_pixel_0.png",
            "test/imgs/Cocoa_pixel_1.png",
            "test/imgs/Cocoa_pixel_2.png",
            "test/imgs/Cocoa_pixel_3.png",
            "test/imgs/Cocoa_pixel_4.png",
            "test/imgs/Cocoa_pixel_5.png",
            "test/imgs/Cocoa_pixel_6.png",
            "test/imgs/Cocoa_pixel_7.png",
            "test/imgs/Cocoa_pixel_8.png",
            "test/imgs/Cocoa_pixel_9.png"
        ],
        "illustration":[
            "test/imgs/Cocoa_illustration_0.png",
            "test/imgs/Cocoa_illustration_1.png",
            "test/imgs/Cocoa_illustration_2.png",
            "test/imgs/Cocoa_illustration_3.png"
        ],
        "image_fps_delay":6
    },
    "attack_list":[
        {
            "queue":1,
            "type":"normal",
            "duration":2700,
            "boundary":[50,50,350,150],
            "hp":4500,
            "rule":[
                {
                    "type":"attack",
                    "time":60,
                    "repeat":{
                        "interval":120,
                        "count":-1
                    },
                    "danmaku_initialized":[
                        {
                            "name":"bbc1",
                            "source":[
                                "test/imgs/big_blue_circle.png"
                            ],
                            "collision_box_size":1,
                            "collidable":True
                        }
                    ],
                    "emitter":[
                        {
                            "name":"bbc1",
                            "layer":1,
                            "amount":61,
                            "continuity":"disposable",
                            "parament":{
                                "index":{
                                    "type":"generator",
                                    "property":{
                                        "name":"range",
                                        "arguments":{
                                            "start":-30,
                                            "stop":31,
                                            "step":1
                                        }
                                    }
                                },
                                "pi":{
                                    "type":"constant",
                                    "property":{
                                        "value":"{math.pi}"
                                    }
                                }
                            },
                            "action":[
                                {
                                    "speed":2.33,
                                    "direction":{
                                        "base":{
                                            "type":"Mobject",
                                            "value":"player"
                                        },
                                        "offset":"{parament.index}*{parament.pi}/60"
                                    },
                                    "position":{
                                        "type":"relative",
                                        "value":"boss"
                                    }
                                }
                            ]
                        }
                    ],
                    "movements":{
                        "init":[100, 100],
                        "extra":[
                            {
                                "time":60,
                                
                            }
                        ]
                    }
                }
            ]
        }
    ]
}

game = dmk.Game()
#game.AddQuiz()
game.run()